

#include "cpu_bitwise.h"

static const bool FALSE_VAL = false;
static const bool TRUE_VAL = true;
static const unsigned char ZERO = 0;
static const unsigned char ONE = 1;
static const unsigned char TWO = 2;
static const unsigned char THREE = 3;
static const unsigned char FOUR = 4;
static const unsigned char FIVE = 5;
static const unsigned char SIX = 6;
static const unsigned char SEVEN = 7;

void populateBitwiseOperands1(Hardware *hardware, InstructionMapping *mappings);
void populateBitwiseOperands2Destinations(Hardware *hardware, InstructionMapping *mappings);
void populateBitwiseOperandsResults(Hardware *hardware, InstructionMapping *mappings);
void populateBitwiseOperandsFlags(Hardware *hardware, InstructionMapping *mappings);

void populateBitwiseInstructions(Hardware *hardware, InstructionMapping *mappings) {
	populateBitwiseOperands1(hardware, mappings);
	populateBitwiseOperands2Destinations(hardware, mappings);
	populateBitwiseOperandsResults(hardware, mappings);
	populateBitwiseOperandsFlags(hardware, mappings);
}

void populateBitwiseOperands1(Hardware *hardware, InstructionMapping *mappings) {

	mappings[OpCode_BIT_0_B].operand1 =
		mappings[OpCode_BIT_0_C].operand1 =
		mappings[OpCode_BIT_0_D].operand1 =
		mappings[OpCode_BIT_0_E].operand1 =
		mappings[OpCode_BIT_0_H].operand1 =
		mappings[OpCode_BIT_0_L].operand1 =
		mappings[OpCode_BIT_0_MEM_HL].operand1 =
		mappings[OpCode_BIT_0_A].operand1 =
		mappings[OpCode_RES_0_B].operand1 =
		mappings[OpCode_RES_0_C].operand1 =
		mappings[OpCode_RES_0_D].operand1 =
		mappings[OpCode_RES_0_E].operand1 =
		mappings[OpCode_RES_0_H].operand1 =
		mappings[OpCode_RES_0_L].operand1 =
		mappings[OpCode_RES_0_MEM_HL].operand1 =
		mappings[OpCode_RES_0_A].operand1 =
		mappings[OpCode_SET_0_B].operand1 =
		mappings[OpCode_SET_0_C].operand1 =
		mappings[OpCode_SET_0_D].operand1 =
		mappings[OpCode_SET_0_E].operand1 =
		mappings[OpCode_SET_0_H].operand1 =
		mappings[OpCode_SET_0_L].operand1 =
		mappings[OpCode_SET_0_MEM_HL].operand1 =
		mappings[OpCode_SET_0_A].operand1 = createGBByteValue(&ZERO);

	mappings[OpCode_BIT_1_B].operand1 =
		mappings[OpCode_BIT_1_C].operand1 =
		mappings[OpCode_BIT_1_D].operand1 =
		mappings[OpCode_BIT_1_E].operand1 =
		mappings[OpCode_BIT_1_H].operand1 =
		mappings[OpCode_BIT_1_L].operand1 =
		mappings[OpCode_BIT_1_MEM_HL].operand1 =
		mappings[OpCode_BIT_1_A].operand1 =
		mappings[OpCode_RES_1_B].operand1 =
		mappings[OpCode_RES_1_C].operand1 =
		mappings[OpCode_RES_1_D].operand1 =
		mappings[OpCode_RES_1_E].operand1 =
		mappings[OpCode_RES_1_H].operand1 =
		mappings[OpCode_RES_1_L].operand1 =
		mappings[OpCode_RES_1_MEM_HL].operand1 =
		mappings[OpCode_RES_1_A].operand1 =
		mappings[OpCode_SET_1_B].operand1 =
		mappings[OpCode_SET_1_C].operand1 =
		mappings[OpCode_SET_1_D].operand1 =
		mappings[OpCode_SET_1_E].operand1 =
		mappings[OpCode_SET_1_H].operand1 =
		mappings[OpCode_SET_1_L].operand1 =
		mappings[OpCode_SET_1_MEM_HL].operand1 =
		mappings[OpCode_SET_1_A].operand1 = createGBByteValue(&ONE);

	mappings[OpCode_BIT_2_B].operand1 =
		mappings[OpCode_BIT_2_C].operand1 =
		mappings[OpCode_BIT_2_D].operand1 =
		mappings[OpCode_BIT_2_E].operand1 =
		mappings[OpCode_BIT_2_H].operand1 =
		mappings[OpCode_BIT_2_L].operand1 =
		mappings[OpCode_BIT_2_MEM_HL].operand1 =
		mappings[OpCode_BIT_2_A].operand1 =
		mappings[OpCode_RES_2_B].operand1 =
		mappings[OpCode_RES_2_C].operand1 =
		mappings[OpCode_RES_2_D].operand1 =
		mappings[OpCode_RES_2_E].operand1 =
		mappings[OpCode_RES_2_H].operand1 =
		mappings[OpCode_RES_2_L].operand1 =
		mappings[OpCode_RES_2_MEM_HL].operand1 =
		mappings[OpCode_RES_2_A].operand1 =
		mappings[OpCode_SET_2_B].operand1 =
		mappings[OpCode_SET_2_C].operand1 =
		mappings[OpCode_SET_2_D].operand1 =
		mappings[OpCode_SET_2_E].operand1 =
		mappings[OpCode_SET_2_H].operand1 =
		mappings[OpCode_SET_2_L].operand1 =
		mappings[OpCode_SET_2_MEM_HL].operand1 =
		mappings[OpCode_SET_2_A].operand1 = createGBByteValue(&TWO);

	mappings[OpCode_BIT_3_B].operand1 =
		mappings[OpCode_BIT_3_C].operand1 =
		mappings[OpCode_BIT_3_D].operand1 =
		mappings[OpCode_BIT_3_E].operand1 =
		mappings[OpCode_BIT_3_H].operand1 =
		mappings[OpCode_BIT_3_L].operand1 =
		mappings[OpCode_BIT_3_MEM_HL].operand1 =
		mappings[OpCode_BIT_3_A].operand1 =
		mappings[OpCode_RES_3_B].operand1 =
		mappings[OpCode_RES_3_C].operand1 =
		mappings[OpCode_RES_3_D].operand1 =
		mappings[OpCode_RES_3_E].operand1 =
		mappings[OpCode_RES_3_H].operand1 =
		mappings[OpCode_RES_3_L].operand1 =
		mappings[OpCode_RES_3_MEM_HL].operand1 =
		mappings[OpCode_RES_3_A].operand1 =
		mappings[OpCode_SET_3_B].operand1 =
		mappings[OpCode_SET_3_C].operand1 =
		mappings[OpCode_SET_3_D].operand1 =
		mappings[OpCode_SET_3_E].operand1 =
		mappings[OpCode_SET_3_H].operand1 =
		mappings[OpCode_SET_3_L].operand1 =
		mappings[OpCode_SET_3_MEM_HL].operand1 =
		mappings[OpCode_SET_3_A].operand1 = createGBByteValue(&THREE);

	mappings[OpCode_BIT_4_B].operand1 =
		mappings[OpCode_BIT_4_C].operand1 =
		mappings[OpCode_BIT_4_D].operand1 =
		mappings[OpCode_BIT_4_E].operand1 =
		mappings[OpCode_BIT_4_H].operand1 =
		mappings[OpCode_BIT_4_L].operand1 =
		mappings[OpCode_BIT_4_MEM_HL].operand1 =
		mappings[OpCode_BIT_4_A].operand1 =
		mappings[OpCode_RES_4_B].operand1 =
		mappings[OpCode_RES_4_C].operand1 =
		mappings[OpCode_RES_4_D].operand1 =
		mappings[OpCode_RES_4_E].operand1 =
		mappings[OpCode_RES_4_H].operand1 =
		mappings[OpCode_RES_4_L].operand1 =
		mappings[OpCode_RES_4_MEM_HL].operand1 =
		mappings[OpCode_RES_4_A].operand1 =
		mappings[OpCode_SET_4_B].operand1 =
		mappings[OpCode_SET_4_C].operand1 =
		mappings[OpCode_SET_4_D].operand1 =
		mappings[OpCode_SET_4_E].operand1 =
		mappings[OpCode_SET_4_H].operand1 =
		mappings[OpCode_SET_4_L].operand1 =
		mappings[OpCode_SET_4_MEM_HL].operand1 =
		mappings[OpCode_SET_4_A].operand1 = createGBByteValue(&FOUR);

	mappings[OpCode_BIT_5_B].operand1 =
		mappings[OpCode_BIT_5_C].operand1 =
		mappings[OpCode_BIT_5_D].operand1 =
		mappings[OpCode_BIT_5_E].operand1 =
		mappings[OpCode_BIT_5_H].operand1 =
		mappings[OpCode_BIT_5_L].operand1 =
		mappings[OpCode_BIT_5_MEM_HL].operand1 =
		mappings[OpCode_BIT_5_A].operand1 =
		mappings[OpCode_RES_5_B].operand1 =
		mappings[OpCode_RES_5_C].operand1 =
		mappings[OpCode_RES_5_D].operand1 =
		mappings[OpCode_RES_5_E].operand1 =
		mappings[OpCode_RES_5_H].operand1 =
		mappings[OpCode_RES_5_L].operand1 =
		mappings[OpCode_RES_5_MEM_HL].operand1 =
		mappings[OpCode_RES_5_A].operand1 =
		mappings[OpCode_SET_5_B].operand1 =
		mappings[OpCode_SET_5_C].operand1 =
		mappings[OpCode_SET_5_D].operand1 =
		mappings[OpCode_SET_5_E].operand1 =
		mappings[OpCode_SET_5_H].operand1 =
		mappings[OpCode_SET_5_L].operand1 =
		mappings[OpCode_SET_5_MEM_HL].operand1 =
		mappings[OpCode_SET_5_A].operand1 = createGBByteValue(&FIVE);

	mappings[OpCode_BIT_6_B].operand1 =
		mappings[OpCode_BIT_6_C].operand1 =
		mappings[OpCode_BIT_6_D].operand1 =
		mappings[OpCode_BIT_6_E].operand1 =
		mappings[OpCode_BIT_6_H].operand1 =
		mappings[OpCode_BIT_6_L].operand1 =
		mappings[OpCode_BIT_6_MEM_HL].operand1 =
		mappings[OpCode_BIT_6_A].operand1 =
		mappings[OpCode_RES_6_B].operand1 =
		mappings[OpCode_RES_6_C].operand1 =
		mappings[OpCode_RES_6_D].operand1 =
		mappings[OpCode_RES_6_E].operand1 =
		mappings[OpCode_RES_6_H].operand1 =
		mappings[OpCode_RES_6_L].operand1 =
		mappings[OpCode_RES_6_MEM_HL].operand1 =
		mappings[OpCode_RES_6_A].operand1 =
		mappings[OpCode_SET_6_B].operand1 =
		mappings[OpCode_SET_6_C].operand1 =
		mappings[OpCode_SET_6_D].operand1 =
		mappings[OpCode_SET_6_E].operand1 =
		mappings[OpCode_SET_6_H].operand1 =
		mappings[OpCode_SET_6_L].operand1 =
		mappings[OpCode_SET_6_MEM_HL].operand1 =
		mappings[OpCode_SET_6_A].operand1 = createGBByteValue(&SIX);

	mappings[OpCode_BIT_7_B].operand1 =
		mappings[OpCode_BIT_7_C].operand1 =
		mappings[OpCode_BIT_7_D].operand1 =
		mappings[OpCode_BIT_7_E].operand1 =
		mappings[OpCode_BIT_7_H].operand1 =
		mappings[OpCode_BIT_7_L].operand1 =
		mappings[OpCode_BIT_7_MEM_HL].operand1 =
		mappings[OpCode_BIT_7_A].operand1 =
		mappings[OpCode_RES_7_B].operand1 =
		mappings[OpCode_RES_7_C].operand1 =
		mappings[OpCode_RES_7_D].operand1 =
		mappings[OpCode_RES_7_E].operand1 =
		mappings[OpCode_RES_7_H].operand1 =
		mappings[OpCode_RES_7_L].operand1 =
		mappings[OpCode_RES_7_MEM_HL].operand1 =
		mappings[OpCode_RES_7_A].operand1 =
		mappings[OpCode_SET_7_B].operand1 =
		mappings[OpCode_SET_7_C].operand1 =
		mappings[OpCode_SET_7_D].operand1 =
		mappings[OpCode_SET_7_E].operand1 =
		mappings[OpCode_SET_7_H].operand1 =
		mappings[OpCode_SET_7_L].operand1 =
		mappings[OpCode_SET_7_MEM_HL].operand1 =
		mappings[OpCode_SET_7_A].operand1 = createGBByteValue(&SEVEN);

	mappings[OpCode_RLCA].operand1 =
		mappings[OpCode_RLA].operand1 =
		mappings[OpCode_RRCA].operand1 =
		mappings[OpCode_RRA].operand1 =
		mappings[OpCode_RL_A].operand1 =
		mappings[OpCode_RLC_A].operand1 =
		mappings[OpCode_RRC_A].operand1 =
		mappings[OpCode_RR_A].operand1 =
		mappings[OpCode_SLA_A].operand1 =
		mappings[OpCode_SRA_A].operand1 =
		mappings[OpCode_SRL_A].operand1 =
		mappings[OpCode_SWAP_A].operand1 = createGBByteValue(&hardware->registers->A);

	mappings[OpCode_SWAP_B].operand1 =
		mappings[OpCode_RLC_B].operand1 =
		mappings[OpCode_RL_B].operand1 =
		mappings[OpCode_RRC_B].operand1 =
		mappings[OpCode_RR_B].operand1 =
		mappings[OpCode_SLA_B].operand1 =
		mappings[OpCode_SRA_B].operand1 =
		mappings[OpCode_SRL_B].operand1 = createGBByteValue(&hardware->registers->B);

	mappings[OpCode_SWAP_C].operand1 =
		mappings[OpCode_RLC_C].operand1 =
		mappings[OpCode_RL_C].operand1 =
		mappings[OpCode_RRC_C].operand1 =
		mappings[OpCode_RR_C].operand1 =
		mappings[OpCode_SLA_C].operand1 =
		mappings[OpCode_SRA_C].operand1 =
		mappings[OpCode_SRL_C].operand1 = createGBByteValue(&hardware->registers->C);
	
	mappings[OpCode_SWAP_D].operand1 =
		mappings[OpCode_RLC_D].operand1 =
		mappings[OpCode_RL_D].operand1 =
		mappings[OpCode_RRC_D].operand1 =
		mappings[OpCode_RR_D].operand1 =
		mappings[OpCode_SLA_D].operand1 =
		mappings[OpCode_SRA_D].operand1 =
		mappings[OpCode_SRL_D].operand1 = createGBByteValue(&hardware->registers->D);
	
	mappings[OpCode_SWAP_E].operand1 =
		mappings[OpCode_RLC_E].operand1 =
		mappings[OpCode_RL_E].operand1 =
		mappings[OpCode_RRC_E].operand1 =
		mappings[OpCode_RR_E].operand1 =
		mappings[OpCode_SLA_E].operand1 =
		mappings[OpCode_SRA_E].operand1 =
		mappings[OpCode_SRL_E].operand1 = createGBByteValue(&hardware->registers->E);
	
	mappings[OpCode_SWAP_H].operand1 =
		mappings[OpCode_RLC_H].operand1 =
		mappings[OpCode_RL_H].operand1 =
		mappings[OpCode_RRC_H].operand1 =
		mappings[OpCode_RR_H].operand1 =
		mappings[OpCode_SLA_H].operand1 =
		mappings[OpCode_SRA_H].operand1 =
		mappings[OpCode_SRL_H].operand1 = createGBByteValue(&hardware->registers->H);
	
	mappings[OpCode_SWAP_L].operand1 =
		mappings[OpCode_RLC_L].operand1 =
		mappings[OpCode_RL_L].operand1 =
		mappings[OpCode_RRC_L].operand1 =
		mappings[OpCode_RR_L].operand1 =
		mappings[OpCode_SLA_L].operand1 =
		mappings[OpCode_SRA_L].operand1 =
		mappings[OpCode_SRL_L].operand1 = createGBByteValue(&hardware->registers->L);
	
	mappings[OpCode_SWAP_MEM_HL].operand1 =
		mappings[OpCode_RLC_MEM_HL].operand1 =
		mappings[OpCode_RL_MEM_HL].operand1 =
		mappings[OpCode_RRC_MEM_HL].operand1 =
		mappings[OpCode_RR_MEM_HL].operand1 =
		mappings[OpCode_SLA_MEM_HL].operand1 =
		mappings[OpCode_SRA_MEM_HL].operand1 =
		mappings[OpCode_SRL_MEM_HL].operand1 = createGBBytePointer(&hardware->cachedValues->memoryHL);
}

void populateBitwiseOperands2Destinations(Hardware *hardware, InstructionMapping *mappings) {
	mappings[OpCode_BIT_0_A].operand2 =
		mappings[OpCode_BIT_1_A].operand2 =
		mappings[OpCode_BIT_2_A].operand2 =
		mappings[OpCode_BIT_3_A].operand2 =
		mappings[OpCode_BIT_4_A].operand2 =
		mappings[OpCode_BIT_5_A].operand2 =
		mappings[OpCode_BIT_6_A].operand2 =
		mappings[OpCode_BIT_7_A].operand2 =
		mappings[OpCode_RLCA].destination =
		mappings[OpCode_RLA].destination =
		mappings[OpCode_RRCA].destination =
		mappings[OpCode_RRA].destination =
		mappings[OpCode_RL_A].destination =
		mappings[OpCode_RLC_A].destination =
		mappings[OpCode_RRC_A].destination =
		mappings[OpCode_RR_A].destination =
		mappings[OpCode_SLA_A].destination =
		mappings[OpCode_SRA_A].destination =
		mappings[OpCode_SRL_A].destination =
		mappings[OpCode_RES_0_A].destination =
		mappings[OpCode_RES_0_A].operand2 =
		mappings[OpCode_RES_1_A].destination =
		mappings[OpCode_RES_1_A].operand2 =
		mappings[OpCode_RES_2_A].destination =
		mappings[OpCode_RES_2_A].operand2 =
		mappings[OpCode_RES_3_A].destination =
		mappings[OpCode_RES_3_A].operand2 =
		mappings[OpCode_RES_4_A].destination =
		mappings[OpCode_RES_4_A].operand2 =
		mappings[OpCode_RES_5_A].destination =
		mappings[OpCode_RES_5_A].operand2 =
		mappings[OpCode_RES_6_A].destination =
		mappings[OpCode_RES_6_A].operand2 =
		mappings[OpCode_RES_7_A].destination =
		mappings[OpCode_RES_7_A].operand2 =
		mappings[OpCode_SET_0_A].destination =
		mappings[OpCode_SET_0_A].operand2 =
		mappings[OpCode_SET_1_A].destination =
		mappings[OpCode_SET_1_A].operand2 =
		mappings[OpCode_SET_2_A].destination =
		mappings[OpCode_SET_2_A].operand2 =
		mappings[OpCode_SET_3_A].destination =
		mappings[OpCode_SET_3_A].operand2 =
		mappings[OpCode_SET_4_A].destination =
		mappings[OpCode_SET_4_A].operand2 =
		mappings[OpCode_SET_5_A].destination =
		mappings[OpCode_SET_5_A].operand2 =
		mappings[OpCode_SET_6_A].destination =
		mappings[OpCode_SET_6_A].operand2 =
		mappings[OpCode_SET_7_A].destination =
		mappings[OpCode_SET_7_A].operand2 = createGBByteValue(&hardware->registers->A);

	mappings[OpCode_BIT_0_B].operand2 =
		mappings[OpCode_BIT_1_B].operand2 =
		mappings[OpCode_BIT_2_B].operand2 =
		mappings[OpCode_BIT_3_B].operand2 =
		mappings[OpCode_BIT_4_B].operand2 =
		mappings[OpCode_BIT_5_B].operand2 =
		mappings[OpCode_BIT_6_B].operand2 =
		mappings[OpCode_BIT_7_B].operand2 =
		mappings[OpCode_RLC_B].destination =
		mappings[OpCode_RL_B].destination =
		mappings[OpCode_RRC_B].destination =
		mappings[OpCode_RR_B].destination =
		mappings[OpCode_SLA_B].destination =
		mappings[OpCode_SRA_B].destination =
		mappings[OpCode_SRL_B].destination =
		mappings[OpCode_RES_0_B].destination =
		mappings[OpCode_RES_0_B].operand2 =
		mappings[OpCode_RES_1_B].destination =
		mappings[OpCode_RES_1_B].operand2 =
		mappings[OpCode_RES_2_B].destination =
		mappings[OpCode_RES_2_B].operand2 =
		mappings[OpCode_RES_3_B].destination =
		mappings[OpCode_RES_3_B].operand2 =
		mappings[OpCode_RES_4_B].destination =
		mappings[OpCode_RES_4_B].operand2 =
		mappings[OpCode_RES_5_B].destination =
		mappings[OpCode_RES_5_B].operand2 =
		mappings[OpCode_RES_6_B].destination =
		mappings[OpCode_RES_6_B].operand2 =
		mappings[OpCode_RES_7_B].destination =
		mappings[OpCode_RES_7_B].operand2 =
		mappings[OpCode_SET_0_B].destination =
		mappings[OpCode_SET_0_B].operand2 =
		mappings[OpCode_SET_1_B].destination =
		mappings[OpCode_SET_1_B].operand2 =
		mappings[OpCode_SET_2_B].destination =
		mappings[OpCode_SET_2_B].operand2 =
		mappings[OpCode_SET_3_B].destination =
		mappings[OpCode_SET_3_B].operand2 =
		mappings[OpCode_SET_4_B].destination =
		mappings[OpCode_SET_4_B].operand2 =
		mappings[OpCode_SET_5_B].destination =
		mappings[OpCode_SET_5_B].operand2 =
		mappings[OpCode_SET_6_B].destination =
		mappings[OpCode_SET_6_B].operand2 =
		mappings[OpCode_SET_7_B].destination =
		mappings[OpCode_SET_7_B].operand2 = createGBByteValue(&hardware->registers->B);

	mappings[OpCode_BIT_0_C].operand2 =
		mappings[OpCode_BIT_1_C].operand2 =
		mappings[OpCode_BIT_2_C].operand2 =
		mappings[OpCode_BIT_3_C].operand2 =
		mappings[OpCode_BIT_4_C].operand2 =
		mappings[OpCode_BIT_5_C].operand2 =
		mappings[OpCode_BIT_6_C].operand2 =
		mappings[OpCode_BIT_7_C].operand2 =
		mappings[OpCode_RLC_C].destination =
		mappings[OpCode_RL_C].destination =
		mappings[OpCode_RRC_C].destination =
		mappings[OpCode_RR_C].destination =
		mappings[OpCode_SLA_C].destination =
		mappings[OpCode_SRA_C].destination =
		mappings[OpCode_SRL_C].destination =
		mappings[OpCode_RES_0_C].destination =
		mappings[OpCode_RES_0_C].operand2 =
		mappings[OpCode_RES_1_C].destination =
		mappings[OpCode_RES_1_C].operand2 =
		mappings[OpCode_RES_2_C].destination =
		mappings[OpCode_RES_2_C].operand2 =
		mappings[OpCode_RES_3_C].destination =
		mappings[OpCode_RES_3_C].operand2 =
		mappings[OpCode_RES_4_C].destination =
		mappings[OpCode_RES_4_C].operand2 =
		mappings[OpCode_RES_5_C].destination =
		mappings[OpCode_RES_5_C].operand2 =
		mappings[OpCode_RES_6_C].destination =
		mappings[OpCode_RES_6_C].operand2 =
		mappings[OpCode_RES_7_C].destination =
		mappings[OpCode_RES_7_C].operand2 =
		mappings[OpCode_SET_0_C].destination =
		mappings[OpCode_SET_0_C].operand2 =
		mappings[OpCode_SET_1_C].destination =
		mappings[OpCode_SET_1_C].operand2 =
		mappings[OpCode_SET_2_C].destination =
		mappings[OpCode_SET_2_C].operand2 =
		mappings[OpCode_SET_3_C].destination =
		mappings[OpCode_SET_3_C].operand2 =
		mappings[OpCode_SET_4_C].destination =
		mappings[OpCode_SET_4_C].operand2 =
		mappings[OpCode_SET_5_C].destination =
		mappings[OpCode_SET_5_C].operand2 =
		mappings[OpCode_SET_6_C].destination =
		mappings[OpCode_SET_6_C].operand2 =
		mappings[OpCode_SET_7_C].destination =
		mappings[OpCode_SET_7_C].operand2 = createGBByteValue(&hardware->registers->C);

	mappings[OpCode_BIT_0_D].operand2 =
		mappings[OpCode_BIT_1_D].operand2 =
		mappings[OpCode_BIT_2_D].operand2 =
		mappings[OpCode_BIT_3_D].operand2 =
		mappings[OpCode_BIT_4_D].operand2 =
		mappings[OpCode_BIT_5_D].operand2 =
		mappings[OpCode_BIT_6_D].operand2 =
		mappings[OpCode_BIT_7_D].operand2 =
		mappings[OpCode_RLC_D].destination =
		mappings[OpCode_RL_D].destination =
		mappings[OpCode_RRC_D].destination =
		mappings[OpCode_RR_D].destination =
		mappings[OpCode_SLA_D].destination =
		mappings[OpCode_SRA_D].destination =
		mappings[OpCode_SRL_D].destination =
		mappings[OpCode_RES_0_D].destination =
		mappings[OpCode_RES_0_D].operand2 =
		mappings[OpCode_RES_1_D].destination =
		mappings[OpCode_RES_1_D].operand2 =
		mappings[OpCode_RES_2_D].destination =
		mappings[OpCode_RES_2_D].operand2 =
		mappings[OpCode_RES_3_D].destination =
		mappings[OpCode_RES_3_D].operand2 =
		mappings[OpCode_RES_4_D].destination =
		mappings[OpCode_RES_4_D].operand2 =
		mappings[OpCode_RES_5_D].destination =
		mappings[OpCode_RES_5_D].operand2 =
		mappings[OpCode_RES_6_D].destination =
		mappings[OpCode_RES_6_D].operand2 =
		mappings[OpCode_RES_7_D].destination =
		mappings[OpCode_RES_7_D].operand2 =
		mappings[OpCode_SET_0_D].destination =
		mappings[OpCode_SET_0_D].operand2 =
		mappings[OpCode_SET_1_D].destination =
		mappings[OpCode_SET_1_D].operand2 =
		mappings[OpCode_SET_2_D].destination =
		mappings[OpCode_SET_2_D].operand2 =
		mappings[OpCode_SET_3_D].destination =
		mappings[OpCode_SET_3_D].operand2 =
		mappings[OpCode_SET_4_D].destination =
		mappings[OpCode_SET_4_D].operand2 =
		mappings[OpCode_SET_5_D].destination =
		mappings[OpCode_SET_5_D].operand2 =
		mappings[OpCode_SET_6_D].destination =
		mappings[OpCode_SET_6_D].operand2 =
		mappings[OpCode_SET_7_D].destination =
		mappings[OpCode_SET_7_D].operand2 = createGBByteValue(&hardware->registers->D);

	mappings[OpCode_BIT_0_E].operand2 =
		mappings[OpCode_BIT_1_E].operand2 =
		mappings[OpCode_BIT_2_E].operand2 =
		mappings[OpCode_BIT_3_E].operand2 =
		mappings[OpCode_BIT_4_E].operand2 =
		mappings[OpCode_BIT_5_E].operand2 =
		mappings[OpCode_BIT_6_E].operand2 =
		mappings[OpCode_BIT_7_E].operand2 =
		mappings[OpCode_RLC_E].destination =
		mappings[OpCode_RL_E].destination =
		mappings[OpCode_RRC_E].destination =
		mappings[OpCode_RR_E].destination =
		mappings[OpCode_SLA_E].destination =
		mappings[OpCode_SRA_E].destination =
		mappings[OpCode_SRL_E].destination =
		mappings[OpCode_RES_0_E].destination =
		mappings[OpCode_RES_0_E].operand2 =
		mappings[OpCode_RES_1_E].destination =
		mappings[OpCode_RES_1_E].operand2 =
		mappings[OpCode_RES_2_E].destination =
		mappings[OpCode_RES_2_E].operand2 =
		mappings[OpCode_RES_3_E].destination =
		mappings[OpCode_RES_3_E].operand2 =
		mappings[OpCode_RES_4_E].destination =
		mappings[OpCode_RES_4_E].operand2 =
		mappings[OpCode_RES_5_E].destination =
		mappings[OpCode_RES_5_E].operand2 =
		mappings[OpCode_RES_6_E].destination =
		mappings[OpCode_RES_6_E].operand2 =
		mappings[OpCode_RES_7_E].destination =
		mappings[OpCode_RES_7_E].operand2 =
		mappings[OpCode_SET_0_E].destination =
		mappings[OpCode_SET_0_E].operand2 =
		mappings[OpCode_SET_1_E].destination =
		mappings[OpCode_SET_1_E].operand2 =
		mappings[OpCode_SET_2_E].destination =
		mappings[OpCode_SET_2_E].operand2 =
		mappings[OpCode_SET_3_E].destination =
		mappings[OpCode_SET_3_E].operand2 =
		mappings[OpCode_SET_4_E].destination =
		mappings[OpCode_SET_4_E].operand2 =
		mappings[OpCode_SET_5_E].destination =
		mappings[OpCode_SET_5_E].operand2 =
		mappings[OpCode_SET_6_E].destination =
		mappings[OpCode_SET_6_E].operand2 =
		mappings[OpCode_SET_7_E].destination =
		mappings[OpCode_SET_7_E].operand2 = createGBByteValue(&hardware->registers->E);

	mappings[OpCode_BIT_0_H].operand2 =
		mappings[OpCode_BIT_1_H].operand2 =
		mappings[OpCode_BIT_2_H].operand2 =
		mappings[OpCode_BIT_3_H].operand2 =
		mappings[OpCode_BIT_4_H].operand2 =
		mappings[OpCode_BIT_5_H].operand2 =
		mappings[OpCode_BIT_6_H].operand2 =
		mappings[OpCode_BIT_7_H].operand2 =
		mappings[OpCode_RLC_H].destination =
		mappings[OpCode_RL_H].destination =
		mappings[OpCode_RRC_H].destination =
		mappings[OpCode_RR_H].destination =
		mappings[OpCode_SLA_H].destination =
		mappings[OpCode_SRA_H].destination =
		mappings[OpCode_SRL_H].destination =
		mappings[OpCode_RES_0_H].destination =
		mappings[OpCode_RES_0_H].operand2 =
		mappings[OpCode_RES_1_H].destination =
		mappings[OpCode_RES_1_H].operand2 =
		mappings[OpCode_RES_2_H].destination =
		mappings[OpCode_RES_2_H].operand2 =
		mappings[OpCode_RES_3_H].destination =
		mappings[OpCode_RES_3_H].operand2 =
		mappings[OpCode_RES_4_H].destination =
		mappings[OpCode_RES_4_H].operand2 =
		mappings[OpCode_RES_5_H].destination =
		mappings[OpCode_RES_5_H].operand2 =
		mappings[OpCode_RES_6_H].destination =
		mappings[OpCode_RES_6_H].operand2 =
		mappings[OpCode_RES_7_H].destination =
		mappings[OpCode_RES_7_H].operand2 =
		mappings[OpCode_SET_0_H].destination =
		mappings[OpCode_SET_0_H].operand2 =
		mappings[OpCode_SET_1_H].destination =
		mappings[OpCode_SET_1_H].operand2 =
		mappings[OpCode_SET_2_H].destination =
		mappings[OpCode_SET_2_H].operand2 =
		mappings[OpCode_SET_3_H].destination =
		mappings[OpCode_SET_3_H].operand2 =
		mappings[OpCode_SET_4_H].destination =
		mappings[OpCode_SET_4_H].operand2 =
		mappings[OpCode_SET_5_H].destination =
		mappings[OpCode_SET_5_H].operand2 =
		mappings[OpCode_SET_6_H].destination =
		mappings[OpCode_SET_6_H].operand2 =
		mappings[OpCode_SET_7_H].destination =
		mappings[OpCode_SET_7_H].operand2 = createGBByteValue(&hardware->registers->H);

	mappings[OpCode_BIT_0_L].operand2 =
		mappings[OpCode_BIT_1_L].operand2 =
		mappings[OpCode_BIT_2_L].operand2 =
		mappings[OpCode_BIT_3_L].operand2 =
		mappings[OpCode_BIT_4_L].operand2 =
		mappings[OpCode_BIT_5_L].operand2 =
		mappings[OpCode_BIT_6_L].operand2 =
		mappings[OpCode_BIT_7_L].operand2 =
		mappings[OpCode_RLC_L].destination =
		mappings[OpCode_RL_L].destination =
		mappings[OpCode_RRC_L].destination =
		mappings[OpCode_RR_L].destination =
		mappings[OpCode_SLA_L].destination =
		mappings[OpCode_SRA_L].destination =
		mappings[OpCode_SRL_L].destination =
		mappings[OpCode_RES_0_L].destination =
		mappings[OpCode_RES_0_L].operand2 =
		mappings[OpCode_RES_1_L].destination =
		mappings[OpCode_RES_1_L].operand2 =
		mappings[OpCode_RES_2_L].destination =
		mappings[OpCode_RES_2_L].operand2 =
		mappings[OpCode_RES_3_L].destination =
		mappings[OpCode_RES_3_L].operand2 =
		mappings[OpCode_RES_4_L].destination =
		mappings[OpCode_RES_4_L].operand2 =
		mappings[OpCode_RES_5_L].destination =
		mappings[OpCode_RES_5_L].operand2 =
		mappings[OpCode_RES_6_L].destination =
		mappings[OpCode_RES_6_L].operand2 =
		mappings[OpCode_RES_7_L].destination =
		mappings[OpCode_RES_7_L].operand2 =
		mappings[OpCode_SET_0_L].destination =
		mappings[OpCode_SET_0_L].operand2 =
		mappings[OpCode_SET_1_L].destination =
		mappings[OpCode_SET_1_L].operand2 =
		mappings[OpCode_SET_2_L].destination =
		mappings[OpCode_SET_2_L].operand2 =
		mappings[OpCode_SET_3_L].destination =
		mappings[OpCode_SET_3_L].operand2 =
		mappings[OpCode_SET_4_L].destination =
		mappings[OpCode_SET_4_L].operand2 =
		mappings[OpCode_SET_5_L].destination =
		mappings[OpCode_SET_5_L].operand2 =
		mappings[OpCode_SET_6_L].destination =
		mappings[OpCode_SET_6_L].operand2 =
		mappings[OpCode_SET_7_L].destination =
		mappings[OpCode_SET_7_L].operand2 = createGBByteValue(&hardware->registers->L);

	mappings[OpCode_BIT_0_MEM_HL].operand2 =
		mappings[OpCode_BIT_1_MEM_HL].operand2 =
		mappings[OpCode_BIT_2_MEM_HL].operand2 =
		mappings[OpCode_BIT_3_MEM_HL].operand2 =
		mappings[OpCode_BIT_4_MEM_HL].operand2 =
		mappings[OpCode_BIT_5_MEM_HL].operand2 =
		mappings[OpCode_BIT_6_MEM_HL].operand2 =
		mappings[OpCode_BIT_7_MEM_HL].operand2 =
		mappings[OpCode_RLC_MEM_HL].destination =
		mappings[OpCode_RL_MEM_HL].destination =
		mappings[OpCode_RRC_MEM_HL].destination =
		mappings[OpCode_RR_MEM_HL].destination =
		mappings[OpCode_SLA_MEM_HL].destination =
		mappings[OpCode_SRA_MEM_HL].destination =
		mappings[OpCode_SRL_MEM_HL].destination =
		mappings[OpCode_RES_0_MEM_HL].destination =
		mappings[OpCode_RES_0_MEM_HL].operand2 =
		mappings[OpCode_RES_1_MEM_HL].destination =
		mappings[OpCode_RES_1_MEM_HL].operand2 =
		mappings[OpCode_RES_2_MEM_HL].destination =
		mappings[OpCode_RES_2_MEM_HL].operand2 =
		mappings[OpCode_RES_3_MEM_HL].destination =
		mappings[OpCode_RES_3_MEM_HL].operand2 =
		mappings[OpCode_RES_4_MEM_HL].destination =
		mappings[OpCode_RES_4_MEM_HL].operand2 =
		mappings[OpCode_RES_5_MEM_HL].destination =
		mappings[OpCode_RES_5_MEM_HL].operand2 =
		mappings[OpCode_RES_6_MEM_HL].destination =
		mappings[OpCode_RES_6_MEM_HL].operand2 =
		mappings[OpCode_RES_7_MEM_HL].destination =
		mappings[OpCode_RES_7_MEM_HL].operand2 =
		mappings[OpCode_SET_0_MEM_HL].destination =
		mappings[OpCode_SET_0_MEM_HL].operand2 =
		mappings[OpCode_SET_1_MEM_HL].destination =
		mappings[OpCode_SET_1_MEM_HL].operand2 =
		mappings[OpCode_SET_2_MEM_HL].destination =
		mappings[OpCode_SET_2_MEM_HL].operand2 =
		mappings[OpCode_SET_3_MEM_HL].destination =
		mappings[OpCode_SET_3_MEM_HL].operand2 =
		mappings[OpCode_SET_4_MEM_HL].destination =
		mappings[OpCode_SET_4_MEM_HL].operand2 =
		mappings[OpCode_SET_5_MEM_HL].destination =
		mappings[OpCode_SET_5_MEM_HL].operand2 =
		mappings[OpCode_SET_6_MEM_HL].destination =
		mappings[OpCode_SET_6_MEM_HL].operand2 =
		mappings[OpCode_SET_7_MEM_HL].destination =
		mappings[OpCode_SET_7_MEM_HL].operand2 = createGBBytePointer(&hardware->cachedValues->memoryHL);

	mappings[OpCode_SWAP_A].destination = createGBByteValue(&hardware->registers->A);
	mappings[OpCode_SWAP_B].destination = createGBByteValue(&hardware->registers->B);
	mappings[OpCode_SWAP_C].destination = createGBByteValue(&hardware->registers->C);
	mappings[OpCode_SWAP_D].destination = createGBByteValue(&hardware->registers->D);
	mappings[OpCode_SWAP_E].destination = createGBByteValue(&hardware->registers->E);
	mappings[OpCode_SWAP_H].destination = createGBByteValue(&hardware->registers->H);
	mappings[OpCode_SWAP_L].destination = createGBByteValue(&hardware->registers->L);
	mappings[OpCode_SWAP_MEM_HL].destination = createGBBytePointer(&hardware->cachedValues->memoryHL);
}

void populateBitwiseOperandsResults(Hardware *hardware, InstructionMapping *mappings) {
	mappings[OpCode_BIT_0_B].operation =
		mappings[OpCode_BIT_0_C].operation =
		mappings[OpCode_BIT_0_D].operation =
		mappings[OpCode_BIT_0_E].operation =
		mappings[OpCode_BIT_0_H].operation =
		mappings[OpCode_BIT_0_L].operation =
		mappings[OpCode_BIT_0_MEM_HL].operation =
		mappings[OpCode_BIT_0_A].operation =
		mappings[OpCode_BIT_1_B].operation =
		mappings[OpCode_BIT_1_C].operation =
		mappings[OpCode_BIT_1_D].operation =
		mappings[OpCode_BIT_1_E].operation =
		mappings[OpCode_BIT_1_H].operation =
		mappings[OpCode_BIT_1_L].operation =
		mappings[OpCode_BIT_1_MEM_HL].operation =
		mappings[OpCode_BIT_1_A].operation =
		mappings[OpCode_BIT_2_B].operation =
		mappings[OpCode_BIT_2_C].operation =
		mappings[OpCode_BIT_2_D].operation =
		mappings[OpCode_BIT_2_E].operation =
		mappings[OpCode_BIT_2_H].operation =
		mappings[OpCode_BIT_2_L].operation =
		mappings[OpCode_BIT_2_MEM_HL].operation =
		mappings[OpCode_BIT_2_A].operation =
		mappings[OpCode_BIT_3_B].operation =
		mappings[OpCode_BIT_3_C].operation =
		mappings[OpCode_BIT_3_D].operation =
		mappings[OpCode_BIT_3_E].operation =
		mappings[OpCode_BIT_3_H].operation =
		mappings[OpCode_BIT_3_L].operation =
		mappings[OpCode_BIT_3_MEM_HL].operation =
		mappings[OpCode_BIT_3_A].operation =
		mappings[OpCode_BIT_4_B].operation =
		mappings[OpCode_BIT_4_C].operation =
		mappings[OpCode_BIT_4_D].operation =
		mappings[OpCode_BIT_4_E].operation =
		mappings[OpCode_BIT_4_H].operation =
		mappings[OpCode_BIT_4_L].operation =
		mappings[OpCode_BIT_4_MEM_HL].operation =
		mappings[OpCode_BIT_4_A].operation =
		mappings[OpCode_BIT_5_B].operation =
		mappings[OpCode_BIT_5_C].operation =
		mappings[OpCode_BIT_5_D].operation =
		mappings[OpCode_BIT_5_E].operation =
		mappings[OpCode_BIT_5_H].operation =
		mappings[OpCode_BIT_5_L].operation =
		mappings[OpCode_BIT_5_MEM_HL].operation =
		mappings[OpCode_BIT_5_A].operation =
		mappings[OpCode_BIT_6_B].operation =
		mappings[OpCode_BIT_6_C].operation =
		mappings[OpCode_BIT_6_D].operation =
		mappings[OpCode_BIT_6_E].operation =
		mappings[OpCode_BIT_6_H].operation =
		mappings[OpCode_BIT_6_L].operation =
		mappings[OpCode_BIT_6_MEM_HL].operation =
		mappings[OpCode_BIT_6_A].operation =
		mappings[OpCode_BIT_7_B].operation =
		mappings[OpCode_BIT_7_C].operation =
		mappings[OpCode_BIT_7_D].operation =
		mappings[OpCode_BIT_7_E].operation =
		mappings[OpCode_BIT_7_H].operation =
		mappings[OpCode_BIT_7_L].operation =
		mappings[OpCode_BIT_7_MEM_HL].operation =
		mappings[OpCode_BIT_7_A].operation = &hardware->operations->getBit;

	mappings[OpCode_RES_0_B].operation =
		mappings[OpCode_RES_0_C].operation =
		mappings[OpCode_RES_0_D].operation =
		mappings[OpCode_RES_0_E].operation =
		mappings[OpCode_RES_0_H].operation =
		mappings[OpCode_RES_0_L].operation =
		mappings[OpCode_RES_0_MEM_HL].operation =
		mappings[OpCode_RES_0_A].operation =
		mappings[OpCode_RES_1_B].operation =
		mappings[OpCode_RES_1_C].operation =
		mappings[OpCode_RES_1_D].operation =
		mappings[OpCode_RES_1_E].operation =
		mappings[OpCode_RES_1_H].operation =
		mappings[OpCode_RES_1_L].operation =
		mappings[OpCode_RES_1_MEM_HL].operation =
		mappings[OpCode_RES_1_A].operation =
		mappings[OpCode_RES_2_B].operation =
		mappings[OpCode_RES_2_C].operation =
		mappings[OpCode_RES_2_D].operation =
		mappings[OpCode_RES_2_E].operation =
		mappings[OpCode_RES_2_H].operation =
		mappings[OpCode_RES_2_L].operation =
		mappings[OpCode_RES_2_MEM_HL].operation =
		mappings[OpCode_RES_2_A].operation =
		mappings[OpCode_RES_3_B].operation =
		mappings[OpCode_RES_3_C].operation =
		mappings[OpCode_RES_3_D].operation =
		mappings[OpCode_RES_3_E].operation =
		mappings[OpCode_RES_3_H].operation =
		mappings[OpCode_RES_3_L].operation =
		mappings[OpCode_RES_3_MEM_HL].operation =
		mappings[OpCode_RES_3_A].operation =
		mappings[OpCode_RES_4_B].operation =
		mappings[OpCode_RES_4_C].operation =
		mappings[OpCode_RES_4_D].operation =
		mappings[OpCode_RES_4_E].operation =
		mappings[OpCode_RES_4_H].operation =
		mappings[OpCode_RES_4_L].operation =
		mappings[OpCode_RES_4_MEM_HL].operation =
		mappings[OpCode_RES_4_A].operation =
		mappings[OpCode_RES_5_B].operation =
		mappings[OpCode_RES_5_C].operation =
		mappings[OpCode_RES_5_D].operation =
		mappings[OpCode_RES_5_E].operation =
		mappings[OpCode_RES_5_H].operation =
		mappings[OpCode_RES_5_L].operation =
		mappings[OpCode_RES_5_MEM_HL].operation =
		mappings[OpCode_RES_5_A].operation =
		mappings[OpCode_RES_6_B].operation =
		mappings[OpCode_RES_6_C].operation =
		mappings[OpCode_RES_6_D].operation =
		mappings[OpCode_RES_6_E].operation =
		mappings[OpCode_RES_6_H].operation =
		mappings[OpCode_RES_6_L].operation =
		mappings[OpCode_RES_6_MEM_HL].operation =
		mappings[OpCode_RES_6_A].operation =
		mappings[OpCode_RES_7_B].operation =
		mappings[OpCode_RES_7_C].operation =
		mappings[OpCode_RES_7_D].operation =
		mappings[OpCode_RES_7_E].operation =
		mappings[OpCode_RES_7_H].operation =
		mappings[OpCode_RES_7_L].operation =
		mappings[OpCode_RES_7_MEM_HL].operation =
		mappings[OpCode_RES_7_A].operation = &hardware->operations->resetBit;

	mappings[OpCode_SET_0_B].operation =
		mappings[OpCode_SET_0_C].operation =
		mappings[OpCode_SET_0_D].operation =
		mappings[OpCode_SET_0_E].operation =
		mappings[OpCode_SET_0_H].operation =
		mappings[OpCode_SET_0_L].operation =
		mappings[OpCode_SET_0_MEM_HL].operation =
		mappings[OpCode_SET_0_A].operation =
		mappings[OpCode_SET_1_B].operation =
		mappings[OpCode_SET_1_C].operation =
		mappings[OpCode_SET_1_D].operation =
		mappings[OpCode_SET_1_E].operation =
		mappings[OpCode_SET_1_H].operation =
		mappings[OpCode_SET_1_L].operation =
		mappings[OpCode_SET_1_MEM_HL].operation =
		mappings[OpCode_SET_1_A].operation =
		mappings[OpCode_SET_2_B].operation =
		mappings[OpCode_SET_2_C].operation =
		mappings[OpCode_SET_2_D].operation =
		mappings[OpCode_SET_2_E].operation =
		mappings[OpCode_SET_2_H].operation =
		mappings[OpCode_SET_2_L].operation =
		mappings[OpCode_SET_2_MEM_HL].operation =
		mappings[OpCode_SET_2_A].operation =
		mappings[OpCode_SET_3_B].operation =
		mappings[OpCode_SET_3_C].operation =
		mappings[OpCode_SET_3_D].operation =
		mappings[OpCode_SET_3_E].operation =
		mappings[OpCode_SET_3_H].operation =
		mappings[OpCode_SET_3_L].operation =
		mappings[OpCode_SET_3_MEM_HL].operation =
		mappings[OpCode_SET_3_A].operation =
		mappings[OpCode_SET_4_B].operation =
		mappings[OpCode_SET_4_C].operation =
		mappings[OpCode_SET_4_D].operation =
		mappings[OpCode_SET_4_E].operation =
		mappings[OpCode_SET_4_H].operation =
		mappings[OpCode_SET_4_L].operation =
		mappings[OpCode_SET_4_MEM_HL].operation =
		mappings[OpCode_SET_4_A].operation =
		mappings[OpCode_SET_5_B].operation =
		mappings[OpCode_SET_5_C].operation =
		mappings[OpCode_SET_5_D].operation =
		mappings[OpCode_SET_5_E].operation =
		mappings[OpCode_SET_5_H].operation =
		mappings[OpCode_SET_5_L].operation =
		mappings[OpCode_SET_5_MEM_HL].operation =
		mappings[OpCode_SET_5_A].operation =
		mappings[OpCode_SET_6_B].operation =
		mappings[OpCode_SET_6_C].operation =
		mappings[OpCode_SET_6_D].operation =
		mappings[OpCode_SET_6_E].operation =
		mappings[OpCode_SET_6_H].operation =
		mappings[OpCode_SET_6_L].operation =
		mappings[OpCode_SET_6_MEM_HL].operation =
		mappings[OpCode_SET_6_A].operation =
		mappings[OpCode_SET_7_B].operation =
		mappings[OpCode_SET_7_C].operation =
		mappings[OpCode_SET_7_D].operation =
		mappings[OpCode_SET_7_E].operation =
		mappings[OpCode_SET_7_H].operation =
		mappings[OpCode_SET_7_L].operation =
		mappings[OpCode_SET_7_MEM_HL].operation =
		mappings[OpCode_SET_7_A].operation == &hardware->operations->setBit;


	mappings[OpCode_SWAP_A].operation =
		mappings[OpCode_SWAP_B].operation =
		mappings[OpCode_SWAP_C].operation =
		mappings[OpCode_SWAP_D].operation =
		mappings[OpCode_SWAP_E].operation =
		mappings[OpCode_SWAP_H].operation =
		mappings[OpCode_SWAP_L].operation =
		mappings[OpCode_SWAP_MEM_HL].operation = &hardware->operations->swapNibbles;

	mappings[OpCode_RLCA].operation =
		mappings[OpCode_RLC_A].operation =
		mappings[OpCode_RLC_B].operation =
		mappings[OpCode_RLC_C].operation =
		mappings[OpCode_RLC_D].operation =
		mappings[OpCode_RLC_E].operation =
		mappings[OpCode_RLC_H].operation =
		mappings[OpCode_RLC_L].operation =
		mappings[OpCode_RLC_MEM_HL].operation = &hardware->operations->rotateRight;

	mappings[OpCode_RLA].operation = 
		mappings[OpCode_RL_A].operation =
		mappings[OpCode_RL_B].operation =
		mappings[OpCode_RL_C].operation =
		mappings[OpCode_RL_D].operation =
		mappings[OpCode_RL_E].operation =
		mappings[OpCode_RL_H].operation =
		mappings[OpCode_RL_L].operation =
		mappings[OpCode_RL_MEM_HL].operation = &hardware->operations->rotateLeftCarry;

	mappings[OpCode_RRCA].operation =
		mappings[OpCode_RRC_A].operation =
		mappings[OpCode_RRC_B].operation =
		mappings[OpCode_RRC_C].operation =
		mappings[OpCode_RRC_D].operation =
		mappings[OpCode_RRC_E].operation =
		mappings[OpCode_RRC_H].operation =
		mappings[OpCode_RRC_L].operation =
		mappings[OpCode_RRC_MEM_HL].operation = &hardware->operations->rotateRight;

	mappings[OpCode_RRA].operation = 
		mappings[OpCode_RR_A].operation =
		mappings[OpCode_RR_B].operation =
		mappings[OpCode_RR_C].operation =
		mappings[OpCode_RR_D].operation =
		mappings[OpCode_RR_E].operation =
		mappings[OpCode_RR_H].operation =
		mappings[OpCode_RR_L].operation =
		mappings[OpCode_RR_MEM_HL].operation = &hardware->operations->rotateRightCarry;


	mappings[OpCode_SLA_A].operation =
		mappings[OpCode_SLA_B].operation =
		mappings[OpCode_SLA_C].operation =
		mappings[OpCode_SLA_D].operation =
		mappings[OpCode_SLA_E].operation =
		mappings[OpCode_SLA_H].operation =
		mappings[OpCode_SLA_L].operation =
		mappings[OpCode_SLA_MEM_HL].operation = &hardware->operations->shiftLeft;

	mappings[OpCode_SRA_A].operation =
		mappings[OpCode_SRA_B].operation =
		mappings[OpCode_SRA_C].operation =
		mappings[OpCode_SRA_D].operation =
		mappings[OpCode_SRA_E].operation =
		mappings[OpCode_SRA_H].operation =
		mappings[OpCode_SRA_L].operation =
		mappings[OpCode_SRA_MEM_HL].operation = &hardware->operations->shiftRightArithmetic;

	mappings[OpCode_SRL_A].operation =
		mappings[OpCode_SRL_B].operation =
		mappings[OpCode_SRL_C].operation =
		mappings[OpCode_SRL_D].operation =
		mappings[OpCode_SRL_E].operation =
		mappings[OpCode_SRL_H].operation =
		mappings[OpCode_SRL_L].operation =
		mappings[OpCode_SRL_MEM_HL].operation = &hardware->operations->shiftRightLogical;
}

void populateBitwiseOperandsFlags(Hardware *hardware, InstructionMapping *mappings) {
	mappings[OpCode_BIT_0_B].flagResult =
		mappings[OpCode_BIT_0_C].flagResult =
		mappings[OpCode_BIT_0_D].flagResult =
		mappings[OpCode_BIT_0_E].flagResult =
		mappings[OpCode_BIT_0_H].flagResult =
		mappings[OpCode_BIT_0_L].flagResult =
		mappings[OpCode_BIT_0_MEM_HL].flagResult =
		mappings[OpCode_BIT_0_A].flagResult =
		mappings[OpCode_BIT_1_B].flagResult =
		mappings[OpCode_BIT_1_C].flagResult =
		mappings[OpCode_BIT_1_D].flagResult =
		mappings[OpCode_BIT_1_E].flagResult =
		mappings[OpCode_BIT_1_H].flagResult =
		mappings[OpCode_BIT_1_L].flagResult =
		mappings[OpCode_BIT_1_MEM_HL].flagResult =
		mappings[OpCode_BIT_1_A].flagResult =
		mappings[OpCode_BIT_2_B].flagResult =
		mappings[OpCode_BIT_2_C].flagResult =
		mappings[OpCode_BIT_2_D].flagResult =
		mappings[OpCode_BIT_2_E].flagResult =
		mappings[OpCode_BIT_2_H].flagResult =
		mappings[OpCode_BIT_2_L].flagResult =
		mappings[OpCode_BIT_2_MEM_HL].flagResult =
		mappings[OpCode_BIT_2_A].flagResult =
		mappings[OpCode_BIT_3_B].flagResult =
		mappings[OpCode_BIT_3_C].flagResult =
		mappings[OpCode_BIT_3_D].flagResult =
		mappings[OpCode_BIT_3_E].flagResult =
		mappings[OpCode_BIT_3_H].flagResult =
		mappings[OpCode_BIT_3_L].flagResult =
		mappings[OpCode_BIT_3_MEM_HL].flagResult =
		mappings[OpCode_BIT_3_A].flagResult =
		mappings[OpCode_BIT_4_B].flagResult =
		mappings[OpCode_BIT_4_C].flagResult =
		mappings[OpCode_BIT_4_D].flagResult =
		mappings[OpCode_BIT_4_E].flagResult =
		mappings[OpCode_BIT_4_H].flagResult =
		mappings[OpCode_BIT_4_L].flagResult =
		mappings[OpCode_BIT_4_MEM_HL].flagResult =
		mappings[OpCode_BIT_4_A].flagResult =
		mappings[OpCode_BIT_5_B].flagResult =
		mappings[OpCode_BIT_5_C].flagResult =
		mappings[OpCode_BIT_5_D].flagResult =
		mappings[OpCode_BIT_5_E].flagResult =
		mappings[OpCode_BIT_5_H].flagResult =
		mappings[OpCode_BIT_5_L].flagResult =
		mappings[OpCode_BIT_5_MEM_HL].flagResult =
		mappings[OpCode_BIT_5_A].flagResult =
		mappings[OpCode_BIT_6_B].flagResult =
		mappings[OpCode_BIT_6_C].flagResult =
		mappings[OpCode_BIT_6_D].flagResult =
		mappings[OpCode_BIT_6_E].flagResult =
		mappings[OpCode_BIT_6_H].flagResult =
		mappings[OpCode_BIT_6_L].flagResult =
		mappings[OpCode_BIT_6_MEM_HL].flagResult =
		mappings[OpCode_BIT_6_A].flagResult =
		mappings[OpCode_BIT_7_B].flagResult =
		mappings[OpCode_BIT_7_C].flagResult =
		mappings[OpCode_BIT_7_D].flagResult =
		mappings[OpCode_BIT_7_E].flagResult =
		mappings[OpCode_BIT_7_H].flagResult =
		mappings[OpCode_BIT_7_L].flagResult =
		mappings[OpCode_BIT_7_MEM_HL].flagResult =
		mappings[OpCode_BIT_7_A].flagResult = createFlagResult(&hardware->resultInfo->isZero, &FALSE_VAL, &TRUE_VAL, NULL);


	mappings[OpCode_SWAP_A].flagResult =
		mappings[OpCode_SWAP_B].flagResult =
		mappings[OpCode_SWAP_C].flagResult =
		mappings[OpCode_SWAP_D].flagResult =
		mappings[OpCode_SWAP_E].flagResult =
		mappings[OpCode_SWAP_H].flagResult =
		mappings[OpCode_SWAP_L].flagResult =
		mappings[OpCode_SWAP_MEM_HL].flagResult = createFlagResult(&hardware->resultInfo->isZero, &FALSE_VAL, &FALSE_VAL, &FALSE_VAL);

	mappings[OpCode_RLCA].flagResult =
		mappings[OpCode_RLA].flagResult = createFlagResult(&FALSE_VAL, &FALSE_VAL, &FALSE_VAL, &hardware->resultInfo->isOperand1Bit7Set);

	mappings[OpCode_RRCA].flagResult =
		mappings[OpCode_RRA].flagResult = createFlagResult(&FALSE_VAL, &FALSE_VAL, &FALSE_VAL, &hardware->resultInfo->isOperand1Bit0Set);
	

	mappings[OpCode_RLC_A].flagResult =
		mappings[OpCode_RLC_B].flagResult =
		mappings[OpCode_RLC_C].flagResult =
		mappings[OpCode_RLC_D].flagResult =
		mappings[OpCode_RLC_E].flagResult =
		mappings[OpCode_RLC_H].flagResult =
		mappings[OpCode_RLC_L].flagResult =
		mappings[OpCode_RLC_MEM_HL].flagResult =
		mappings[OpCode_RL_A].flagResult =
		mappings[OpCode_RL_B].flagResult =
		mappings[OpCode_RL_C].flagResult =
		mappings[OpCode_RL_D].flagResult =
		mappings[OpCode_RL_E].flagResult =
		mappings[OpCode_RL_H].flagResult =
		mappings[OpCode_RL_L].flagResult =
		mappings[OpCode_RL_MEM_HL].flagResult =
		mappings[OpCode_SLA_A].flagResult =
		mappings[OpCode_SLA_B].flagResult =
		mappings[OpCode_SLA_C].flagResult =
		mappings[OpCode_SLA_D].flagResult =
		mappings[OpCode_SLA_E].flagResult =
		mappings[OpCode_SLA_H].flagResult =
		mappings[OpCode_SLA_L].flagResult =
		mappings[OpCode_SLA_MEM_HL].flagResult = createFlagResult(&hardware->resultInfo->isZero, &FALSE_VAL, &FALSE_VAL, &hardware->resultInfo->isOperand1Bit7Set);

	mappings[OpCode_RRC_A].flagResult =
		mappings[OpCode_RRC_B].flagResult =
		mappings[OpCode_RRC_C].flagResult =
		mappings[OpCode_RRC_D].flagResult =
		mappings[OpCode_RRC_E].flagResult =
		mappings[OpCode_RRC_H].flagResult =
		mappings[OpCode_RRC_L].flagResult =
		mappings[OpCode_RRC_MEM_HL].flagResult =
		mappings[OpCode_RR_A].flagResult =
		mappings[OpCode_RR_B].flagResult =
		mappings[OpCode_RR_C].flagResult =
		mappings[OpCode_RR_D].flagResult =
		mappings[OpCode_RR_E].flagResult =
		mappings[OpCode_RR_H].flagResult =
		mappings[OpCode_RR_L].flagResult =
		mappings[OpCode_RR_MEM_HL].flagResult =
		mappings[OpCode_SRA_A].flagResult =
		mappings[OpCode_SRA_B].flagResult =
		mappings[OpCode_SRA_C].flagResult =
		mappings[OpCode_SRA_D].flagResult =
		mappings[OpCode_SRA_E].flagResult =
		mappings[OpCode_SRA_H].flagResult =
		mappings[OpCode_SRA_L].flagResult =
		mappings[OpCode_SRA_MEM_HL].flagResult =
		mappings[OpCode_SRL_A].flagResult =
		mappings[OpCode_SRL_B].flagResult =
		mappings[OpCode_SRL_C].flagResult =
		mappings[OpCode_SRL_D].flagResult =
		mappings[OpCode_SRL_E].flagResult =
		mappings[OpCode_SRL_H].flagResult =
		mappings[OpCode_SRL_L].flagResult =
		mappings[OpCode_SRL_MEM_HL].flagResult = createFlagResult(&hardware->resultInfo->isZero, &FALSE_VAL, &FALSE_VAL, &hardware->resultInfo->isOperand1Bit0Set);
}